config/routes.rb
Rails.application.routes.draw do
  root "parcels#index"
  get 'info' => 'info#list', as: 'list'
  get "/parcels" =>  "parcels#index", as: 'index'
  get "/info/from" => "info#showFrom", as: 'showFrom'
  get "/info/value" => "info#showValue", as:'showValue'
  get "/info/repeated" => "info#showRepeated", as: 'showRepeated'

  resources :parcels
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/parcel.rb
class Parcel < ApplicationRecord
    validates :city, presence: true 
    validates :street, presence: true 
    validates :house, presence: true
    validates :appartment, presence: true
    validates :addressee, presence: true
    validates :value, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def index
    end
end

app/controllers/info_controller.rb
class InfoController < ApplicationController

    def showFrom
        @amount_from_Kyiv = find_parcels_from_city
    end

    def showValue
        @amount_above_value = find_parcels_with_value_amount
        @list_of_cities = find_parcels_with_value_list
    end

    def showRepeated
        @list_of_addressees = find_multiple_deliveries
    end

    def find_parcels_from_city()
        array = Parcel.all
        res = array.select {|i| i.city == "Kyiv"}
        res.size
    end
      
    def find_parcels_with_value_amount()
        array = Parcel.all
        res = array.select {|i| i.value > 1000}.map{|i| i.city}
        res.size
    end

    def find_parcels_with_value_list()
        array = Parcel.all
        res = array.select {|i| i.value > 1000}.map{|i| i.city}
        res.uniq
    end
      
    def find_multiple_deliveries()
        addresses = Hash.new(0)
        parcels = Parcel.all
        parcels.each do |parcel|
          addressee = "#{parcel.city}-#{parcel.street}-#{parcel.house}-#{parcel.appartment}"
          addresses[addressee] += 1
        end
        addresses.select{ |_, count| count > 1}
    end  
end

app/controllers/parcels_controller.rb
class ParcelsController < ApplicationController

  http_basic_authenticate_with name: "log", password: "pass"
  http_basic_authenticate_with name: "destroy", password: "pass", only: :destroy
  def index
    @parcels=Parcel.all
  end

  def new
    @parcel = Parcel.new()
  end

  def create
    @parcel = Parcel.new(parcel_params)
    if @parcel.save
      redirect_to @parcel
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @parcel =   Parcel.find(params[:id])
  end

  def destroy
    @parcel = Parcel.find(params[:id])
    @parcel.destroy
    redirect_to root_path, status: :see_other
  end

  def edit
    @parcel = Parcel.find(params[:id])
  end

  def update
    @parcel = Parcel.find(params[:id])
    if  @parcel.update(parcel_params)
      redirect_to @parcel
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private 
  def parcel_params
    params.require(:parcel).permit(:city, :street, :house, :appartment, :addressee, :value)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/info_helper.rb
module InfoHelper
end

app/helpers/parcels_helper.rb
module ParcelsHelper
end

app/views/info/list.html.erb
<h1 style="background-color: #4F6367; color: #FFFFFF; padding: 10px; border-radius: 5px;">Requests that are available:</h1>

<p style="background-color: #B8D8D8; padding: 10px; border-radius: 5px; margin-bottom: 15px;">Parcels sent to Kyiv</p>
<%= link_to "Check", showFrom_path, style: "display: inline-block; padding: 10px; background-color: #4F6367; color: #ffffff; text-decoration: none; border-radius: 5px; transition: background-color 0.3s; margin-bottom: 15px;" %>

<p style="background-color: #B8D8D8; padding: 10px; border-radius: 5px; margin-bottom: 15px;">Parcels whose value is more than UAH 1,000</p>
<%= link_to "Check", showValue_path, style: "display: inline-block; padding: 10px; background-color: #4F6367; color: #ffffff; text-decoration: none; border-radius: 5px; transition: background-color 0.3s; margin-bottom: 15px;" %>

<p style="background-color: #B8D8D8; padding: 10px; border-radius: 5px; margin-bottom: 15px;">Parcels sent to the same address</p>
<%= link_to "Check", showRepeated_path, style: "display: inline-block; padding: 10px; background-color: #4F6367; color: #ffffff; text-decoration: none; border-radius: 5px; transition: background-color 0.3s; margin-bottom: 15px;" %>

app/views/info/showFrom.html.erb
<h3 style="background-color: #4F6367; color: #FFFFFF; padding: 10px; border-radius: 5px;">How many parcels were sent to Kyiv?</h3>

<p style="background-color: #B8D8D8; padding: 10px; border-radius: 5px; margin-bottom: 15px; display: inline-block;">
  <span style="color: #FE5F55; font-weight: bold;">Answer:</span>
  <span style="background-color: #FE5F55; color: #ffffff; padding: 5px 10px; border-radius: 5px; margin-left: 5px;">
    <%= @amount_from_Kyiv %>
  </span>
</p>

app/views/info/showRepeated.html.erb
<h3 style="background-color: #4F6367; color: #FFFFFF; padding: 10px; border-radius: 5px;">Regular customers</h3>


<p style="background-color: #B8D8D8; padding: 10px; border-radius: 5px; margin-bottom: 15px; display: inline-block;">
  <span style="color: #FE5F55; font-weight: bold;">Answer:</span>

  <% @list_of_addressees.each do |addressee, count| %>
    <p style="background-color: #4F6367; color: #ffffff; padding: 5px 10px; border-radius: 5px; margin-left: 5px;"">
      <%= "#{count} parcels were sent to #{addressee}" %>
    </p>
  <% end %>
  
</p>

app/views/info/showValue.html.erb
<h3 style="background-color: #4F6367; color: #FFFFFF; padding: 10px; border-radius: 5px;">Sort by price</h3>

<h5 style="background-color: #B8D8D8;  padding: 10px; border-radius: 5px;">How many parcels worth more than UAH 1000?</h5>
<p style="background-color: #B8D8D8; padding: 10px; border-radius: 5px; margin-bottom: 15px; display: inline-block;">
  <span style="color: #FE5F55; font-weight: bold;">Answer:</span>
  <span style="background-color: #FE5F55; color: #ffffff; padding: 5px 10px; border-radius: 5px; margin-left: 5px;">
    <%= @amount_above_value %>
  </span>
</p>

<p style="background-color: #B8D8D8; color: #FE5F55; padding: 10px; border-radius: 5px; margin-bottom: 15px;">
 <b> List of cities: </b>
</p>

<p style="background-color: #4F6367; color: #FFFFFF; padding: 10px; border-radius: 5px; margin-bottom: 15px;">
  <%= @list_of_cities.join(", ") %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/parcels/_form.html.erb
<%= form_with model: @parcel do |form| %>
  <div style="margin-bottom: 15px; background-color: #B8D8D8; padding: 15px; border-radius: 10px;">
    <%= form.label :city, style: "display: block; font-weight: bold; margin-bottom: 5px;" %><br>
    <%= form.text_field :city, style: "width: 100%; padding: 8px; border: 1px solid #ccc; border-radius: 5px;" %>
    <% @parcel.errors.full_messages_for(:city).each do |message| %>
      <div style="color: #FF0000; margin-top: 5px;"><%= message %></div>
    <% end %>
  </div>

  <div style="margin-bottom: 15px; background-color: #B8D8D8; padding: 15px; border-radius: 10px;">
    <%= form.label :street, style: "display: block; font-weight: bold; margin-bottom: 5px;" %><br>
    <%= form.text_field :street, style: "width: 100%; padding: 8px; border: 1px solid #ccc; border-radius: 5px;" %>
    <% @parcel.errors.full_messages_for(:street).each do |message| %>
      <div style="color: #FF0000; margin-top: 5px;"><%= message %></div>
    <% end %>
  </div>

  <div style="margin-bottom: 15px; background-color: #B8D8D8; padding: 15px; border-radius: 10px;">
    <%= form.label :house, style: "display: block; font-weight: bold; margin-bottom: 5px;" %><br>
    <%= form.text_field :house, style: "width: 100%; padding: 8px; border: 1px solid #ccc; border-radius: 5px;" %>
    <% @parcel.errors.full_messages_for(:house).each do |message| %>
      <div style="color: #FF0000; margin-top: 5px;"><%= message %></div>
    <% end %>
  </div>

  <div style="margin-bottom: 15px; background-color: #B8D8D8; padding: 15px; border-radius: 10px;">
  <%= form.label :appartment, style: "display: block; font-weight: bold; margin-bottom: 5px;" %><br>
  <%= form.text_field :appartment, style: "width: 100%; padding: 8px; border: 1px solid #ccc; border-radius: 5px;" %>
  <% @parcel.errors.full_messages_for(:appartment).each do |message| %>
    <div style="color: #FF0000; margin-top: 5px;"><%= message %></div>
  <% end %>
</div>

<div style="margin-bottom: 15px; background-color: #B8D8D8; padding: 15px; border-radius: 10px;">
  <%= form.label :addressee, style: "display: block; font-weight: bold; margin-bottom: 5px;" %><br>
  <%= form.text_field :addressee, style: "width: 100%; padding: 8px; border: 1px solid #ccc; border-radius: 5px;" %>
  <% @parcel.errors.full_messages_for(:addressee).each do |message| %>
    <div style="color: #FF0000; margin-top: 5px;"><%= message %></div>
  <% end %>
</div>

<div style="margin-bottom: 15px; background-color: #B8D8D8; padding: 15px; border-radius: 10px;">
  <%= form.label :value, style: "display: block; font-weight: bold; margin-bottom: 5px;" %><br>
  <%= form.text_area :value, style: "width: 100%; padding: 8px; border: 1px solid #ccc; border-radius: 5px;" %>
  <% @parcel.errors.full_messages_for(:value).each do |message| %>
    <div style="color: #FF0000; margin-top: 5px;"><%= message %></div>
  <% end %>
</div>


  <div style="margin-bottom: 15px;">
    <%= form.submit style: "padding: 10px; background-color: #4F6367; color: #ffffff; border: none; border-radius: 5px; cursor: pointer;" %>
  </div>
<% end %>

app/views/parcels/edit.html.erb
<h1 style="background-color: #4F6367; color: #FFFFFF; padding: 10px; border-radius: 5px;">Edit Parcel</h1>

<%= render "form", parcel: @parcel %>

app/views/parcels/index.html.erb
<h1 style="background-color: #4F6367; color: #ffffff;margin-bottom: 0;">Postal sorting</h1>

<h3 style="background-color: #7A9E9F;  ">All our customers</h3>

<ul style="list-style: none; padding: 0;">
  <% @parcels.each do |parcel| %>
    <li style="margin-bottom: 10px;">
      <%= link_to parcel.addressee, parcel, style: "display: block; padding: 10px; background-color: #B8D8D8; border-radius: 5px; text-decoration: none; color: #333; transition: background-color 0.3s;" %>
    </li>
  <% end %>
</ul>


<%= link_to "New Parcel", new_parcel_path, class: "rounded-button", style: "background-color: #FE5F55; color: #ffffff; padding: 10px 15px; text-decoration: none;" %>

<%= link_to "Information", list_path, class: "rounded-button", style: "background-color: #7A9E9F; color: #ffffff; padding: 10px 15px; text-decoration: none;" %>

app/views/parcels/new.html.erb
<h1 style="background-color: #4F6367; color: #FFFFFF; padding: 10px; border-radius: 5px;">New Parcel</h1>

<%= render "form", parcel: @parcel %>

app/views/parcels/show.html.erb
<h1 style="background-color: #4F6367; color: #FFFFFF; padding: 10px; border-radius: 5px;">Information about the parcel</h1>

<p style="background-color: #B8D8D8; padding: 10px; border-radius: 5px;">  <b>City: </b> <%=@parcel.city %></p>
<p style="background-color: #B8D8D8; padding: 10px; border-radius: 5px;"> <b>Street: </b> <%= @parcel.street %></p>
<p style="background-color: #B8D8D8; padding: 10px; border-radius: 5px;"> <b>House: </b><%= @parcel.house %></p>
<p style="background-color: #B8D8D8; padding: 10px; border-radius: 5px;"> <b>Apartment: </b><%= @parcel.appartment %></p>
<p style="background-color: #B8D8D8; padding: 10px; border-radius: 5px;"> <b>Addressee: </b><%= @parcel.addressee %></p>
<p style="background-color: #B8D8D8; padding: 10px; border-radius: 5px;"> <b>Value: </b><%= @parcel.value %></p>


<ul style="list-style: none; padding: 0; display: flex;">
  <li style="margin-right: 10px;">
    <%= link_to "Edit", edit_parcel_path(@parcel), style: "display: inline-block; padding: 10px; background-color: #7A9E9F; color: #ffffff; border-radius: 5px; text-decoration: none;" %>
  </li>
  <li>
    <%= link_to "Destroy", parcel_path(@parcel), data: {
      turbo_method: :delete,
      turbo_confirm: "Are you sure?"
    }, style: "display: inline-block; padding: 10px; background-color: #FE5F55; color: #ffffff; border-radius: 5px; text-decoration: none;" %>
  </li>
</ul>